# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optimon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roptimon.proto\x12\nhelloworld\"\x1e\n\x0eGetDataRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0fGetDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"%\n\x10HeartBeatRequest\x12\x11\n\theartbeat\x18\x01 \x01(\t\"$\n\x11HeartBeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9b\x01\n\x07Optimon\x12J\n\tHeartBeat\x12\x1c.helloworld.HeartBeatRequest\x1a\x1d.helloworld.HeartBeatResponse\"\x00\x12\x44\n\x07GetData\x12\x1a.helloworld.GetDataRequest\x1a\x1b.helloworld.GetDataResponse\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_GETDATAREQUEST = DESCRIPTOR.message_types_by_name['GetDataRequest']
_GETDATARESPONSE = DESCRIPTOR.message_types_by_name['GetDataResponse']
_HEARTBEATREQUEST = DESCRIPTOR.message_types_by_name['HeartBeatRequest']
_HEARTBEATRESPONSE = DESCRIPTOR.message_types_by_name['HeartBeatResponse']
GetDataRequest = _reflection.GeneratedProtocolMessageType('GetDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDATAREQUEST,
  '__module__' : 'optimon_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.GetDataRequest)
  })
_sym_db.RegisterMessage(GetDataRequest)

GetDataResponse = _reflection.GeneratedProtocolMessageType('GetDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDATARESPONSE,
  '__module__' : 'optimon_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.GetDataResponse)
  })
_sym_db.RegisterMessage(GetDataResponse)

HeartBeatRequest = _reflection.GeneratedProtocolMessageType('HeartBeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'optimon_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HeartBeatRequest)
  })
_sym_db.RegisterMessage(HeartBeatRequest)

HeartBeatResponse = _reflection.GeneratedProtocolMessageType('HeartBeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRESPONSE,
  '__module__' : 'optimon_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HeartBeatResponse)
  })
_sym_db.RegisterMessage(HeartBeatResponse)

_OPTIMON = DESCRIPTOR.services_by_name['Optimon']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _GETDATAREQUEST._serialized_start=29
  _GETDATAREQUEST._serialized_end=59
  _GETDATARESPONSE._serialized_start=61
  _GETDATARESPONSE._serialized_end=92
  _HEARTBEATREQUEST._serialized_start=94
  _HEARTBEATREQUEST._serialized_end=131
  _HEARTBEATRESPONSE._serialized_start=133
  _HEARTBEATRESPONSE._serialized_end=169
  _OPTIMON._serialized_start=172
  _OPTIMON._serialized_end=327
# @@protoc_insertion_point(module_scope)
